name: trino-deployment
on: [push]
jobs:
  deploy-trino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'https://github.com/trinodb/trino'
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - run: ./mvnw clean install -DskipTests
